### ISSUE TITLE
Unit tests for non Norwegians

### ISSUE THREAD

**Issue by fraschfn** [anjdreas/UnitsNet#103]
Not a real issue but in your unit tests (UnitsNet/UnitsNet.Tests/UnitSystemTests.cs) you assume the current ui culture to be always for Norway. While this might hold true for you, it probably will not for others.

       [Test]
        public void AllUnitsImplementToStringForNorwegian()
        {
            CultureInfo originalCulture = Thread.CurrentThread.CurrentUICulture;
            try
            {
                Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture; // <-- here

**Comment by anjdreas** [comment]
Thanks, must have been a mistake. InvariantCulture will never be Norwegian, regardless of environment. It is a distinct culture on its own. CurrentUICulture however depends on the environment it runs in.
