### ISSUE TITLE
NuGet Package Targeting dnxcore50

### ISSUE THREAD

**Issue by jeremy-bridges** [anjdreas/UnitsNet#107]
I cannot include the NuGet package as a dependency of any portable library. I get an error related to its targeting of dnxcore50. See the following blog post for details:

https://oren.codes/2015/07/29/targeting-net-core/

Here's the error I get when I try to add the reference to a portable library:

![image](https://cloud.githubusercontent.com/assets/3229453/10050221/91254ed4-61d8-11e5-9fb7-85a7ef961e2c.png)

**Comment by anjdreas** [comment]
Thanks. Do you by chance want to take a stab at fixing it? My time is a bit limited these days.

**Comment by anjdreas** [comment]
I think the next step is to support .NET Standard. DNX is already made obsolete.

**Comment by anjdreas** [comment]
Will be fixed by #196 (I think).
