### ISSUE TITLE
Unit Definition Name Convention for Acre Units (USSurvey and International)?

### ISSUE THREAD

**Issue by cumminsjp** [anjdreas/UnitsNet#109]
I am realizing that I need to make a distinction between the 2 acre units, USSurvey and International.

I am not seeing a unit naming convention in the existing code--is there one?  

I first went with `"SingularName": "InternationalAcre"`, but a `"SingularName": "AcreInternational"` and `"SingularName": "AcreUSSurvey"` produces intuitive intellisense.

Or are unqualified units assumed to be international (like in the Mile unit definition in Length.json)?

Thoughts?

**Comment by anjdreas** [comment]
We've usually landed on the namings used in wikipedia, or whichever is the most commonly used in that domain.

Examples being `LongTon` vs `ShortTon` vs `Tonne`, all commonly referred to as tons or tonnes in certain contexts. Another example is `UsGallon` and `UsOunce` volumes.

We have no precedence in grouping units on a common prefix, such as `TonLong`, `TonShort`. I see the point and I can appreciate the benefit, but it does not read very well, so I would vote for `InternationalAcre` and `UsSurveyAcre` in your case - as named by wikipedia. Note the lowercase 's' in Us, as I personally prefer to not capitalize abbreviations as it often leads to less readable names, and there is also a precedence on that in the library.

**Comment by anjdreas** [comment]
I'm closing this due to low activity, reopen if necessary.
