### ISSUE TITLE
Abbreviation for CubicFootPerSecond is wrong

### ISSUE THREAD

**Issue by peter172sp** [anjdreas/UnitsNet#110]
in UnitsNet/GeneratedCode/UnitSystem.Default.g.cs
lines 453-457:
			new CulturesForEnumValue((int) FlowUnit.CubicFootPerSecond,
                            new[]
                            {
                                new AbbreviationsForCulture("en-US", "ft³/h"),
                            }), 
							
The abbreviation should be "ft³/s"

**Comment by anjdreas** [comment]
Thanks for pointing it out, do you mind creating a PR for the fix?
Fix the .json definition file and regenerate the source code.

**Comment by peter172sp** [comment]
pull request created

**Comment by anjdreas** [comment]
PR #111 merged.

**Comment by anjdreas** [comment]
Nuget 3.19.2 published with fix.
