### ISSUE TITLE
Suggest simpler syntax for creating quantity

### ISSUE THREAD

**Issue by surrealist** [anjdreas/UnitsNet#115]
Normally, we create a length this way:

```c#
Length x = Length.FromMeters(1);
Length y = Length.FromMeters(5);
```

I'd successfully code as the following via new c# 6 "using static" statement.

```c#
using static Namespace.StaticClass;
...
Length x = Length(1).Meter;
Length y = Length(5).Meters;
```

`Length()` is a public static function of *StaticClass* and `Meters` is a property that return a new instance of **Length**. BTW, I think that `Length(5).Meters` is more naturally to read than `(5).Meters()` that use the extension method syntax.

**Comment by anjdreas** [comment]
I'm not sold on the benefit here. It's possible I'm not acquainted with the new C# 6 syntax yet, but I don't find the last example more readable. In fact I find it a bit ambiguous. Especially if you rewrite it like this `var x = Length(1).Meters`, it could be read as first creating a Length of 1 (of whatever default unit, I would assume meters) and then returning that length as meters.

On the other hand, static extension method as proposed in https://github.com/anjdreas/UnitsNet/issues/37 offer a significantly improved syntax in my opinion, at least a whole lot shorter. We're using similar for TimeSpan at work with `1.s()` to create 1 second TimeSpan, and the team likes that simplication.

**Comment by surrealist** [comment]
After read your answer twice. I agree with you on that. Thanks.

**Comment by anjdreas** [comment]
Cool, I'll close this discussion then. Thanks for bringing it up.
