### ISSUE TITLE
UnitsNet.PressureChangeRate missing BaseUnit property

### ISSUE THREAD

**Issue by robrisner** [anjdreas/UnitsNet#117]
The PressureChangeRate struct is missing a "BaseUnit" property. All other units of measure contain a property called "BaseUnit" that returns the base unit of measure. Is it possible to add this property to PressureChangeRate? Thanks.

**Comment by anjdreas** [comment]
Thanks for pointing this out. I regenerated the code and pushed a new nuget 3.21.1.
Sometimes when merging in pull requests it has outdated generated code.
