### ISSUE TITLE
International Unit (Pharmacology)

### ISSUE THREAD

**Issue by neutmute** [anjdreas/UnitsNet#126]
Hello - I'm writing an app that needs to process nutrient info. Vitamin A is stored in International Units - [see here](https://developer.calorieking.com/food-api/documentation#Nutrients)

[International Units](https://en.wikipedia.org/wiki/International_unit) are widely used in pharmacology it appears (I'm not an expert in this domain) but it is specific to each thing being measured. ie: 10 IU of Vitamin A is not the same mass or volume for Vitamin D. 

Any suggestions on how to deal with this? 

I guess I should make my own custom type since 1 IU of Vitamin A cannot be added to 1 IU of Vitamin D. 
For for all the other nutrient dimensions that have kJ, mg I'd use the standard Units.NET types.

**Comment by anjdreas** [comment]
Hi, not familiar with those units myself, but from your description I agree with your approach. Create new units like VitaminAQuantity and VitaminDQuantity, with different calculations in their construction methods e.g. FromInternationalUnit() and their conversion properties e.g. InternationalUnit.
This way you have different types to represent these incompatible quantities even though they have similar units names. 

This domain seems widely used to me so if you want to do a pull request I'd be happy to merge it in.
See the readme for how to add new units and creating a PR.

**Comment by anjdreas** [comment]
If you want conversions from VitaminA and D to kJ, mg and other units, you add those other units to both A and D with different conversion functions. If that makes sense. 

Just ask if anything is unclear,  but read the readme for instructions.

**Comment by anjdreas** [comment]
You can also add conversions to Volume, Mass and such unit classes. Add a VitaminAQuantity.extra.cs file with a manually written partial class. See ither .extra.cs files for inspiration.

**Comment by neutmute** [comment]
Excellent tips. I had only thought of making an 'International Unit', not 'VitaminA' unit. 
PR submitted :)
