### ISSUE TITLE
Cup as VolumeUnit

### ISSUE THREAD

**Issue by neutmute** [anjdreas/UnitsNet#130]
Hi again! 
I'm working on a food nutrition system and we need to be able to reference the volume unit of cup (see [wiki def](https://en.wikipedia.org/wiki/Cup_%28unit%29)).

[UnitsNet.Unit.VolumeUnit](https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/GeneratedCode/Enums/VolumeUnit.g.cs) has `Teaspoon `and `Tablespoon` but no _Cup_.

I propose adding:
* MetricCup (250mL)

I don't need US Cups for now but would be happy to add to help clarify the distinction. There are two(!) US cups. Their names might be
* UsCustomaryCup
* UsLegalCup

Would a PR for `MetricCup` be accepted?

**Comment by anjdreas** [comment]
Absolutely :-) sounds good.

**Comment by neutmute** [comment]
#131 submitted
