### ISSUE TITLE
Microsoft Certification warning "NCalc.dll has failed the NXCheck check."

### ISSUE THREAD

**Issue by james1301** [anjdreas/UnitsNet#166]
Hi,

I am trying to certify my WPF application with Microsoft but I am getting the following warning with NCalc:

Warning: The binary analyzer test detected the following errors:◦File C:\Program Files (x86)\Streets Heaver\Compucare8\NCalc.dll has failed the NXCheck check.

I don't know if there is anything you should be doing or me? But I am using a fair few different third party assemblies, but this is the only warning I am getting.

Thanks,
James

**Comment by anjdreas** [comment]
Hi @james1301 , it seems to me you are having problems with a different component than Units.NET?
There is no NCalc or NXCheck in this library.

**Comment by anjdreas** [comment]
Or is NCalc your product, and only after adding NCalc did you receive this warning? If so, please can you make absolutely sure that the warnings goes away when removing Units.NET lib from your product.

I'm not familiar with this certification and can't tell you what possibly it complains about, maybe there is a log file you can read for more details?

**Comment by james1301** [comment]
So sorry you're perfectly correct, I'm being an idiot...

**Comment by anjdreas** [comment]
No worries :-) good luck figuring it out.
