### ISSUE TITLE
Feature Request: Add MassFlowUnit.KilogramPerHour

### ISSUE THREAD

**Issue by enterprisebug** [anjdreas/UnitsNet#167]
in MassFlowUnit enum add support for KilogramPerHour.

MassFlowUnit.KilogramPerSecond is already present.

**Comment by MarcDrexler** [comment]
Please read  https://github.com/anjdreas/UnitsNet/wiki/Adding-a-New-Unit

**Comment by enterprisebug** [comment]
Thanks for clarification. Didn't see that. This is a quite detailed explanation! Will do a contrib.

**Comment by anjdreas** [comment]
Thanks, let's continue in PR.
