### ISSUE TITLE
Density Conversions are Incorrect

### ISSUE THREAD

**Issue by massonib** [anjdreas/UnitsNet#172]
I found four errors in the density conversions. Please see below.

public double KilogramsPerCubicCentimeter
        {
            //Was this // get { return _kilogramsPerCubicMeter*0.00000001; }
            get { return _kilogramsPerCubicMeter* 1e-6; }
        }

        public double KilogramsPerCubicMillimeter
        {
            //Was this // get { return _kilogramsPerCubicMeter*0.000000000001; }
            get { return _kilogramsPerCubicMeter*1e-9; }
        }

        public double TonnesPerCubicCentimeter
        {
            //Was this // get { return _kilogramsPerCubicMeter*0.00000000001; }
            get { return _kilogramsPerCubicMeter* 1e-9; }
        }

        public double TonnesPerCubicMillimeter
        {
            //Was this // get { return _kilogramsPerCubicMeter*0.000000000000001; }
            get { return _kilogramsPerCubicMeter* 1e-12; }
        }

**Comment by eriove** [comment]
Hmm. Looking at the tests and comparing it to Googles unit conversion these seems to be correct. 

        protected override double KilogramsPerCubicCentimeterInOneKilogramPerCubicMeter => 1e-6;

        protected override double KilogramsPerCubicMillimeterInOneKilogramPerCubicMeter => 1e-9;

        protected override double TonnesPerCubicCentimeterInOneKilogramPerCubicMeter => 1e-9;

        protected override double TonnesPerCubicMillimeterInOneKilogramPerCubicMeter => 1e-12;

But just looking at this code it seems wrong...

Not sure what I'm missing.

**Comment by massonib** [comment]
Yes, those are correct. The error is in the Density.g.cs file in the properties region.

**Comment by massonib** [comment]
New .json file

{
  "Name": "Density",
  "BaseUnit": "KilogramPerCubicMeter",
  "XmlDoc": "The density, or more precisely, the volumetric mass density, of a substance is its mass per unit volume.",
  "XmlDocRemarks": "http://en.wikipedia.org/wiki/Density",
  "Units": [
    {
      "SingularName": "KilogramPerCubicMillimeter",
      "PluralName": "KilogramsPerCubicMillimeter",
      "FromUnitToBaseFunc": "x*1e+9",
      "FromBaseToUnitFunc": "x*1e-9",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "kg/mm³" ]
        }
      ]
    },
    {
      "SingularName": "KilogramPerCubicCentimeter",
      "PluralName": "KilogramsPerCubicCentimeter",
      "FromUnitToBaseFunc": "x*1e+6",
      "FromBaseToUnitFunc": "x*1e-6",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "kg/cm³" ]
        }
      ]
    },
    {
      "SingularName": "KilogramPerCubicMeter",
      "PluralName": "KilogramsPerCubicMeter",
      "FromUnitToBaseFunc": "x",
      "FromBaseToUnitFunc": "x",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "kg/m³" ]
        },
        {
          "Culture": "ru-RU",
          "Abbreviations": [ "кг/м³" ]
        }
      ]
    },
    {
      "SingularName": "PoundPerCubicInch",
      "PluralName": "PoundsPerCubicInch",
      "FromUnitToBaseFunc": "x*27679.904710191",
      "FromBaseToUnitFunc": "x/27679.904710191",
      "Prefixes": [ "Kilo" ],
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "lb/in³" ],
          "AbbreviationsWithPrefixes": [ "kip/in³" ]
        }
      ]
    },
    {
      "SingularName": "PoundPerCubicFoot",
      "PluralName": "PoundsPerCubicFoot",
      "FromUnitToBaseFunc": "x/0.062427961",
      "FromBaseToUnitFunc": "x*0.062427961",
      "Prefixes": [ "Kilo" ],
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "lb/ft³" ],
          "AbbreviationsWithPrefixes": [ "kip/ft³" ]
        }
      ]
    },
    {
      "SingularName": "TonnePerCubicMillimeter",
      "PluralName": "TonnesPerCubicMillimeter",
      "FromUnitToBaseFunc": "x*1e+12",
      "FromBaseToUnitFunc": "x*1e-12",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "t/mm³" ]
        }
      ]
    },
    {
      "SingularName": "TonnePerCubicCentimeter",
      "PluralName": "TonnesPerCubicCentimeter",
      "FromUnitToBaseFunc": "x*1e+9",
      "FromBaseToUnitFunc": "x*1e-9",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "t/cm³" ]
        }
      ]
    },
    {
      "SingularName": "TonnePerCubicMeter",
      "PluralName": "TonnesPerCubicMeter",
      "FromUnitToBaseFunc": "x*1000",
      "FromBaseToUnitFunc": "x*0.001",
      "Localization": [
        {
          "Culture": "en-US",
          "Abbreviations": [ "t/m³" ]
        }
      ]
    }
  ]
}

**Comment by massonib** [comment]
Created pull request with fix.

**Comment by anjdreas** [comment]
Fixed in #173
