### ISSUE TITLE
Can't compile with VS2010

### ISSUE THREAD

**Issue by dtsvetkov** [anjdreas/UnitsNet#175]
Seems compilation for 4.0 platform is not supported now.
Some constructions in code like the following looks from the newer version of .net: 
`public static KinematicViscosityUnit ToStringDefaultUnit { get; set; } = KinematicViscosityUnit.SquareMeterPerSecond;`

Is it possible somehow to compile the library from VS2010?

**Comment by anjdreas** [comment]
Hi @dtsvetkov, it's true we are using C#6 syntax in the code, which requires [special steps for VS2013](http://stackoverflow.com/questions/27093908/how-to-enable-c-sharp-6-0-feature-in-visual-studio-2013). I don't believe VS2010 or VS2012 supports C#6, not sure.

We could revert back to C#5 syntax, but honestly with [VS2015 Community](https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx) being 100% free I don't see a big reason to cater for older versions.

**Comment by anjdreas** [comment]
.NET 3.5 is still a supported target, so the title was misleading.

**Comment by anjdreas** [comment]
What are your thoughts on this?

**Comment by dtsvetkov** [comment]
I think we can close this issue. The problem was solved with VS2015 + ReSharper tools.
Sorry for disturbance.

**Comment by anjdreas** [comment]
Absolutely no problem! :-) Glad you got it sorted out.
