### ISSUE TITLE
Why does this arithmetic fail? 

### ISSUE THREAD

**Issue by abelfiore** [anjdreas/UnitsNet#182]
Why does this fail?

Length a = Length.FromYards(35) - Length.FromYards(24);
Length j = a / 2;
Length k = Length.FromYards(5.5);
Assert.AreEqual(j, k);

**Comment by anjdreas** [comment]
I would suspect a type of rounding error. The underlying type is 'double',
and you can't really perform equality checks reliably on it. The value is
likely 5.499999991 or something.

The recommended solution for comparing floating point types is something
like

`bool equal = Math.Abs(a -  b) < 0.00001;`

I suppose it would be an improvement if the Equals methods required an
error margin parameter to highlight that equality checks are prone to
rounding errors.

>

**Comment by anjdreas** [comment]
Closing, will reopen if there are any further discussions.
