### ISSUE TITLE
Storage size

### ISSUE THREAD

**Issue by StevenLiekens** [anjdreas/UnitsNet#183]
Please add a unit for storage size

```c#
using UnitsNet;
```
```c#
byte[] buffer = new byte[Storage.FromKilobytes(64).Bytes];
```
```c#
using (var file = File.OpenWrite("blob.bin"))
{
    file.SetLength(Storage.FromGigabytes(4).LongByteCount);
}
```

**Comment by anjdreas** [comment]
`Information.FromKilobytes(64).Bytes == 64000`

Please note the difference between `Kilobytes` and `Kibibytes`, which is a big source of confusion.

**Comment by anjdreas** [comment]
Also, please note we use `double` type on the API, mostly to be consistent with the other unit types, but the backing type is `long`. This means there should not be a problem with rounding errors, but I have not tested this extensively.

**Comment by StevenLiekens** [comment]
Is it possible to add KiB/MiB/... to the Information unit?
