### ISSUE TITLE
LINQ transform extensions for each unit

### ISSUE THREAD

**Issue by StevenLiekens** [anjdreas/UnitsNet#184]
I'd like there to be overloads for LINQ extensions that take a transform function: `Min`, `Max`, `Sum` and `Average`

Right now LINQ transforms are already possible but awkward to write.

```c#
var values = new List<Length>
{
    new Length(2),
    new Length(4)
};
var sum = new Length(values.Sum(length => length.As(Length.BaseUnit)));
```

It should be as simple as this.
```c#
var sum = values.Sum();
```

Same for `values.Min()`, `values.Max()` and `values.Average()`.

**Comment by anjdreas** [comment]
I've come across the same scenario myself and although I have wanted the same thing, there are a couple of things I'm thinking about.

1. To keep things strongly typed, to avoid summing lengths and volumes, we would need an extension method per type. This means this needs to be generated by the powershell scripts. Should be easy enough to do, but it is a little bit of effort to implement and write tests for.

2. This does not scale very well, and I am concerned about bloating the library. I want it to stay lean.

I did come up with a fairly short way of calculating the sum, but it is not reusable for other LINQ stuff like Average. Below is just a thought experiment trying to avoid duplicating the extension methods, but it didn't really work out.

```
public static class MyEx
{
	public static T Sum<T>(this IEnumerable<T> seq, Func<T, double> toValue, Func<double, T> fromValue)
	{
		return fromValue(seq.Sum(toValue));
	}
	
	public static T Average<T>(this IEnumerable<T> seq, Func<T, double> toValue, Func<double, T> fromValue)
	{
		return fromValue(seq.Average(toValue));
	}
}

void Main()
{
	var lengths = new[] { new Length(1), new Length(2)};
	
	// Sum/average with LINQ
	Console.WriteLine(lengths.Aggregate((a,b) => a + b));
	Console.WriteLine(Length.FromMeters(lengths.Sum(l => l.Meters)));
	Console.WriteLine(Length.FromMeters(lengths.Average(l => l.Meters)));
	
	// Sum/average with generic custom extension methods, not really improving things
	Console.WriteLine(lengths.Sum(x => x.Meters, Length.FromMeters));
	Console.WriteLine(lengths.Average(x => x.Meters, Length.FromMeters));
}
```

I think I am inclined to not generate N extension methods for N unit types. The benefit is not really significant. Writing Sum and Average helper methods per-app is trivial and not much code, but the library size significantly increases by introducing this, and will continue to increase as the number of units grow.

What do you think?

**Comment by StevenLiekens** [comment]
You can make it generic if you change every unit to implement an interface that returns its underlying value.

```c#
interface IUnit
{
    decimal AsBaseUnit();
}
```

Then the extensions would look like this.

```c#
public static T Sum<T>(this IEnumerable<T> seq) where T : IUnit
{
    var sum = seq.Sum(value => value.AsBaseUnit());
    return Activator.CreateInstance(typeof(T), new [] { sum });
}

**Comment by anjdreas** [comment]
Well, that is the thing. As soon as we expose IUnit with a base unit value, all type safety is out the door. If there was a really compelling reason for that, sure, but not just to get a slightly easier Sum() and Average() story.
I'm not a fan of using reflection to achieve this. It's just a slippery slope of running into runtime errors in the future, not to mention performance.

As it stands, I see no good alternative to achieve this.

**Comment by eriove** [comment]
I've also missed the Sum() and Average() but not enough to actually implement something.

If you are worried about bloating the library it would be quite easy to add it as an extra DLL/NuGet package with only the extension methods. For me it doesn't warrant the work required to do this but it would be a nice way of adding the feature for those who need it without including it in the base library.

**Comment by anjdreas** [comment]
Any further input here or can we close this?

**Comment by anjdreas** [comment]
Closing, will reopen if there are any further discussions.
