### ISSUE TITLE
PK Sound is using UnitsNet!

### ISSUE THREAD

**Issue by JKSnd** [anjdreas/UnitsNet#191]
Hi @anjdreas, and thanks for UnitsNet. We at @PkSound have been using UnitsNet for a while in a proprietary software project.

We liked it so much we decided to use it as part of an adapter we're developing to give the MathNet.Spatial project units! Check it out [here](https://github.com/PkSound/Spatial).

I'm bringing this to your attention so we could lend our logo to your "Who are Using This?" section on the UnitsNet readme. What size would you prefer?

Looking forward to your response!

**Comment by anjdreas** [comment]
Hey, that is awesome! Glad you like it and build things on top of it.
I just updated the readme with logo specs.

> Max logo size is 300x35 pixels and should be in .png, .gif or .jpg formats.

Could you also please formulate a text section similar to what I did for Motion Catalyst?
* 1-2 sentences on your organization and what you do, and how you applied Units.NET. 
* A couple of links to your org and any products/projects where Units.NET was employed.
* Your full name and title, or just the username if you prefer

**Comment by JKSnd** [comment]
Awesome! Being a developer and not a graphics artist, I'm having a really hard time exporting our logo to 35x35 while maintaining any decent resolution. 

On Monday I'll get our graphics team to help me out.

For the other parts...

PK Sound
Award-winning performers and composers put everything they’ve got into their music. PK Sound makes sure their fans will hear it all – brilliantly, precisely, consistently.

PK Sound uses UnitsNet in Kontrol - the remote control counterpart to Trinity, the world's only robotic line array solution.
http://www.pksound.ca/trinity/
http://www.pksound.ca

- Jules LaPrairie, Kontrol software team member

**Comment by JKSnd** [comment]
OH and maybe this link, please http://www.pksound.ca/pk-sound/announcing-the-official-release-of-kontrol/

Thank you!

**Comment by anjdreas** [comment]
Great, I put it into the readme. I'll update it when you have the logo ready.

**Comment by JKSnd** [comment]
![pk-logo-black 35x35](https://cloud.githubusercontent.com/assets/17773454/19447800/5c6ec76c-945c-11e6-90f8-3f410e8157b9.jpg)

Here's a 35x35 version of our logo. Thanks for including us @anjdreas
