### ISSUE TITLE
Adding overloads

### ISSUE THREAD

**Issue by JKSnd** [anjdreas/UnitsNet#192]
I've noticed that Force.extras.cs contains some operator overloads and some static factory methods.
I want to add an operator overload for F=ma, and an overload for FromMassByAcceleration so that it takes an Acceleration instance instead of a double.

I looked in the Wiki for guidance on this kind of edit. I found information on how to start a unit from scratch, but I couldn't determine if adding overloads should just be done by editing *.extra.cs files or through a code-generating script.

Thanks in advance for your help.

**Comment by anjdreas** [comment]
Ah, yes that is not documented at all I realized. You are on the right track though. Additional unit class code that is not generated, should sit in the extra.cs files. These files are edited by hand.

Does that answer your question ?

**Comment by JKSnd** [comment]
Great! It does, thank you. I'm looking forward to offering up my first pull request on this project.
