### ISSUE TITLE
Resharper Settings are Incomplete

### ISSUE THREAD

**Issue by JKSnd** [anjdreas/UnitsNet#193]
I'm really happy to see that this project includes a R# solution team settings file! Good stuff!

However, I use a computer-wide settings file that is fairly exhaustive. I've noticed that my computer-wide settings file has a great number more settings defined than the Units.Net solution file. This means that when I try to get R# to format the code automatically, the result seems too drastic a change to be inline with what I assume @anjdreas would expect.

I don't suppose using a combination of Resharper's "Save To <layer>" and "Copy Settings To" features would make it possible to flatten your local settings and extend the Units.Net solution settings file?

I've been reading these: [Copy Settings To](https://www.jetbrains.com/help/resharper/2016.2/Sharing_Configuration_Options.html#copy_settings) and [Save To Layer](https://www.jetbrains.com/help/resharper/2016.2/Sharing_Configuration_Options.html#saveTo), but my gut tells me you may already know these things.

**Comment by anjdreas** [comment]
Right, I noticed there are no code styling rules in the .DotSettings file. I suppose I generally don't store a lot of settings per computer. I do have this one file that I share between my computers, but it's pretty sparse and I find myself sticking to the R# default settings most of the time. For bigger projects, we spend some time setting up solution team-shared settings at my company, but very little personal stuff.

I did try to copy some settings from This Computer and from my MyPersonalSettings file, but they are more or less empty. I don't know how I can copy the entire "effective" R# settings into Units.NET's solution team-shared settings file, but I think that might be the solution here so it overrides other people's personal settings on code style.

Do you know how to do that?

**Comment by anjdreas** [comment]
Seems this might be an unsolved problem at the time:
http://stackoverflow.com/a/31378822
https://youtrack.jetbrains.com/issue/RSRP-444671

So far it looks like I would have to manually assign a bunch of code style options for the Units.NET solution team-shared setting.

**Comment by JKSnd** [comment]
Well, that's a bummer.

The little strategy in the "Update 1" section of the SO question sounds like it would work, but it also sounds very annoying to do.

I suppose for now I'll try my best not to pollute UnitsNet files with my resharper code style. 

Thanks for looking into it a bit! I'm going to watch those issues just in case something changes.

Shall we close this one?

**Comment by anjdreas** [comment]
Sure, if you don't mind I'll close this for now until we find a better strategy.
