### ISSUE TITLE
Json serialization alpha release

### ISSUE THREAD

**Issue by JKSnd** [anjdreas/UnitsNet#203]
Commit 7a61bc568b3585b3fc06f3899aa845a01372abd3 is a very useful bugfix for the serialization library, but it was created after the current release on nuget (1.0.0-alpha3).

I've run up against this bug in my project, so I'm hoping that an alpha-4 could be released with this bugfix included?

FYI: I verified that my issue is resolved by using the source code of the UnitsNetJsonConverter directly in my project and it worked very well.

**Comment by anjdreas** [comment]
Oh, I was not aware. Nice catch.

**Comment by JKSnd** [comment]
Thank you! Will do.

**Comment by JKSnd** [comment]
The new nuget package allowed me to move forward with my project. Thanks again!
