### ISSUE TITLE
Elasticity vs. pressure

### ISSUE THREAD

**Issue by VBP8501** [anjdreas/UnitsNet#210]
Hello,

I just wanted to inform that in structural mechanics the elasticity of a material has the same units as pressure. It can be confusing to use a class called Pressure for this unit. What would be the best solution in this case?
1) live with it and use the "Pressure" class
2) introduce the concept of synonym, for example introduce the class "Elasticity" that inherits from "Pressure"
3) copy everything from the "Pressure" class and start a new class called "Elasticity"

**Comment by anjdreas** [comment]
Unfortunately we can't inherit unit types, due to using `struct` not `class`. 
We can, however, generate a duplicate unit if that makes a lot of sense, but if `Pressure` covers your needs it may make sense to use that. I'm not sure. I can imagine several similar cases of other units ideally having their own type name, but their units being identical to another. Not sure we want to add duplicate units for each case, as we would probably bloat the library more than necessary.

**Comment by JKSnd** [comment]
If generating a duplicate happens, should the existing json be extended to include an Alisases property? If the parser detects that there are aliases, then it will generate a seperate but (functionally) identical struct for each. Just spit-balling over here.

**Comment by anjdreas** [comment]
Sure, that would be one way to go about it. Another would be to have a new .json file for each type, declaring that it inherits/aliases some unit. But I really don't like the idea of starting to alias/copy types, I think it's a slippery slope of adding a lot of bloat.

**Comment by JKSnd** [comment]
I agree. This hints at eventually breaking the project out into sub-projects that contain sets of units organized by discipline, I think. I'm not sure how much of a case there is at the moment for such a large effort though.

**Comment by VBP8501** [comment]
I've added this in a seperate branch on my repository by just creating a new unit. If you'd like to implement it in the official version, just let me know. (I need this for my own project)

**Comment by anjdreas** [comment]
Thanks for the heads up. My current point of view is that this belongs in the application code if it's a matter of pure aliasing. If we get more cases of this we might have a better foundation to decide on how to deal with alias units.
