### ISSUE TITLE
Introduce unit for thermal expansion coefficient

### ISSUE THREAD

**Issue by VBP8501** [anjdreas/UnitsNet#211]
Hello,

Would there be an interest to have a PR for a new unit for the thermal expansion coefficient? This basically 1/Temperature unit (so 1/K)

**Comment by anjdreas** [comment]
Does it make sense to convert between multiple units of TEC? If so, yes. If it is just a single unit, we have in some previous cases said it will be up to the application or a different library to add thes types of units. We're not entirely decided on a guideline here.

**Comment by VBP8501** [comment]
I've added this in a seperate branch on my repository. If you'd like to implement it in the official version, just let me know. (I need this for my own project)

**Comment by anjdreas** [comment]
So I found this converter: http://www.unitconversion.org/unit_converter/thermal-expansion.html

Seems it makes sense to convert between different units, so I would say yes, this belong in the core lib.

**Comment by VBP8501** [comment]
Ok so I understand that you would like me to create a pull request for this?
In that case, I'm not entirely sure how to go about this when I also have the changes for the forcePerLength implemented in that branch. I can keep the perTemperature branch updated with the changes in the distributedForce branch offcourse but if I do a pull request, both changes would be open for review and you'll need to do double the work. Any hints? :)

**Comment by anjdreas** [comment]
It requires a tiny bit of git magic. Here is what I propose you do, but the actual steps depends on what git client you are using (GUI or command line).

* Create a new branch pointing to your current branch (eg: `git branch feature/thermal-expansion name-of-existing-branch`)
* Check out the new branch (eg: `git checkout feature/thermal-expansion`)
* Rebase the new branch and drop the changes that are not relevant. If you have been a good boy and kept the changes isolated in two commits, you simply skip the other commit. Eg: `git rebase --interactive origin/master`. If you have mixed changes then I propose you squash the commits into one commit, then hand-edit out the parts that are not relevant and `git commit --amend` to update that one commit.
* Then you checkout the other, original branch and rebase that on top of the thermal expansion branch, eg: `git checkout my-other-branch` and `git rebase feature/thermal-expansion`. You might get some git merge conflicts, but they should be easy enough to handle as you only want to apply non-thermal-expansion code in this branch.
* When the PR gets merged into origin/master you can rebase your local branch on top of that, while on the original branch `git rebase origin/master`, and you should now have the "official" thermal expansion code in your branch.

Some sources on rebase, amend and generally rewriting git history.
https://www.atlassian.com/git/tutorials/rewriting-history/ 
https://git-scm.com/book/en/Git-Tools-Rewriting-History

**Comment by anjdreas** [comment]
I think this can be closed now, reopen if necessary.
