### ISSUE TITLE
U.S. Survey Foot?

### ISSUE THREAD

**Issue by mludlum** [anjdreas/UnitsNet#213]
Is Foot in this library derived from 1 inch = 2.54 cm?  If so, any plans to support the U.S. Survey Foot which is derived from 1200/3937 meters?

**Comment by anjdreas** [comment]
First time I've heard of it, but you are welcome to add it. See the readme on contributing new units.

**Comment by mludlum** [comment]
I've never done a pull request but I'll give it a shot.  

Would it be confusing  to only create a USSurveyFoot unit even though the conversion from USSurveyFoot -> Meter -> Yard does not produce a US Survey Yard?  I didn't want to clutter the units with USSurveyYard, USSurveyMile, etc.

**Comment by JKSnd** [comment]
I wouldn't find it confusing. A Yard is a Yard is a Yard is a Yard. As far as cluttering goes, there is a precedent already. Volume has many US-specific variants already.

@anjdreas, we often comment and recognize the pressure this library is under to include highly niche units. This one makes me wonder if localization might also be they key. There could be a UnitsNet.Core module that contains basic SI units only, and then packages like UnitsNet.UnitedStates to house US specific units like the UsGallon and UsServeyFoot.

**Comment by mludlum** [comment]
I created a pull request with just one unit added.

**Comment by anjdreas** [comment]
@mludlum Thanks!
