### ISSUE TITLE
Pressure.PoundForcePerSquareInch vs Pressure.Psi redundant and inconsistent

### ISSUE THREAD

**Issue by BrandonLWhite** [anjdreas/UnitsNet#215]
There are 2 Pressure units for what I think is technically the same thing: [Pounds per square inch](https://en.wikipedia.org/wiki/Pounds_per_square_inch)

PoundForcePerSquareInch is defined with a conversion factor of 6894.75788951576 and Psi is 6.89464975179*1e3.

I cannot determine where the Psi factor came from. I cannot locate this in any references I checked.  While these are certainly very close, they are different.

I believe the following issues should be addressed:

- There should not be 2 different unit entries for this.  

- Psi should be removed and the "psi" abbreviation added to PoundForcePerSquareInch. I further think "psi" should be the first/preferred abbreviation.

- The conversion factor for PoundForcePerSquareInch should be adjusted to 6.894757293168e3.  This isn't very critical, but so long as the current conversion has a large number of significant digits, they should be correct.  See  http://math.stackexchange.com/questions/64880/pascals-to-psi-formula and https://en.wikipedia.org/wiki/Pounds_per_square_inch

**Comment by anjdreas** [comment]
Funny you should bring that up, I just realized the same thing the other day I was working with pressure. I kind of brushed it off as "meh", but I'm glad you are addressing this. I didn't realize the conversion functions were different, that's not good.

I agree with all your points. Would you care to do a PR?

**Comment by anjdreas** [comment]
By the way, the Psi unit should be marked as `[Obsolete]` and added to #180 for removal in next major version bump. See how [Volume.Teaspoon]9https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/Scripts/UnitDefinitions/Volume.json#L272) is made obsolete.

**Comment by BrandonLWhite** [comment]
Ok great. Sure I can do this.
