### ISSUE TITLE
Is there a Unit to represent Volt-ampere Reactive (var)

### ISSUE THREAD

**Issue by JenTechSystems** [anjdreas/UnitsNet#221]
We're writing a system that needs to convert quantities between units relating to electricity power transmission and distribution.

As such, we need to represent values in Volt-ampere Reactive.
See: https://en.wikipedia.org/wiki/Volt-ampere_reactive

Is there an appropriate unit in Units.Net for this?

**Comment by anjdreas** [comment]
Hi, no we don't currently have this unit.
What would you name this unit class, and what are the names of units you would want to convert between (if any)?

**Comment by anjdreas** [comment]
By the way, I found an older issue that also touches on the `var` unit. I

**Comment by anjdreas** [comment]
By the way, I found an older issue that also touches on the var unit. Please continue this conversation there, so I can close this issue as a duplicate.

https://github.com/anjdreas/UnitsNet/issues/185
