### ISSUE TITLE
Failing to parse Micro units

### ISSUE THREAD

**Issue by JenTechSystems** [anjdreas/UnitsNet#223]
Hi there,

I have a weird situation where I pass in what I think is the correct abbreviation for a Micro scale unit, but it fails.

Here is the unit test:

        [Test]
        public void GetAllElectricalPotentialAbbreviations()
        {
            UnitSystem usUnits = UnitSystem.GetCached(GetCulture("en-US"));

            var abbreviations = usUnits.GetAllAbbreviations(ElectricPotentialUnit.Microvolt);
            Assert.AreEqual("μV", abbreviations[0]);
            Assert.AreEqual("µV", abbreviations[0]);
            Assert.AreEqual("μV", "µV");
        }

Here is the result, which fails on the **second** assertion:

  String lengths are both 2. Strings differ at index 0.
  Expected: "µV"
  But was:  "μV"
  -----------^

It seems like this WYSIWYG editor makes the differences in the encoding more visually obvious.

In fact, none of the editors i have used so far (include Visual Studio) have made a distinction between the two characters.

But how do i correctly deal with this difference programmatically?

**Comment by JenTechSystems** [comment]
Turns out this is due to different encoding being used.

Someone on stackoverflow answered this for me.

The question here, now is: should the Units.Net accomodate for different encodings when we attempt to Parse an abbreviation as such:

`ElectricPotential.ParseUnit("μV") // This parses out correctly`

`ElectricPotential.ParseUnit("µV") // This throws an exception`

**Comment by anjdreas** [comment]
Huh, nice find. I was not aware of this duality. I assume a search and replace is in  order, to get all units to use the correct symbol.
Could you do the PR?

**Comment by anjdreas** [comment]
Both json files and ps1 files, since prefixes are defined in powershell.

**Comment by anjdreas** [comment]
Closing this, conversation continues in PR #224
