### ISSUE TITLE
5µV (Microvolts) is coming back as 4.9999999999999996E-06

### ISSUE THREAD

**Issue by JenTechSystems** [anjdreas/UnitsNet#225]
Converting 5µV to Volts is coming back as 4.9999999999999996E-06 instead of 5E-06 .

But converting 1µV to Volts is coming back correctly as 1E-06.

**Comment by anjdreas** [comment]
Welcome to the nature of `double` and floating point arithmetic. Some decimals it can represent me accurately than others.

It is unfortunate, but I don't really see a good solution to this. ToString() does rounding to alleviate the problem, but one must take care to not perform == equality as with any other double representation. If I recall correctly we dropped == operator overloads for that purpose, and added Equals methods with an error delta.
