### ISSUE TITLE
How to extend a given Unit class

### ISSUE THREAD

**Issue by JenTechSystems** [anjdreas/UnitsNet#227]
I need to add a new type of unit to the Frequency class.

Well, at least I think it belongs there.

Our application needs to be aware of a unit called 'cycle' where we need to convert:

 cycles to ms (20ms=1cycle) (and vice versa)
 cycles to s (0.02s=1cycle) (and vice versa)

Where is the most appropriate place to put this conversion?

**Comment by anjdreas** [comment]
This would be best added as a partial class `Frequency.extra.cs` in the CustomCode folder.

I suppose something like this:
```csharp
public TimeSpan Period => 1.0 / Hertz;
public static Frequency FromPeriod(TimeSpan period) => 1.0 / period.TotalSeconds;
```

**Comment by anjdreas** [comment]
Closing this due to PR #229.
