### ISSUE TITLE
add "From" with SI Factor as overload to LengthUnit and others

### ISSUE THREAD

**Issue by lordzero83** [anjdreas/UnitsNet#230]
I´ve got the SI Factor in my Database like -3, which equals to your FromMillimeter. 
But i dont want to use Unit Parsing "mm" to get the Length Unit.

Maybe use an overload with another switch statement for the Factor and call there the "FromMillimeter" method

**Comment by anjdreas** [comment]
Hi, I'm not sure I follow. Could you please provide a short code snippet that illustrates what you want to achieve?

**Comment by lordzero83** [comment]
`using System;
using NUnit.Framework;
using UnitsNet.Units;

namespace Tests
{
    [TestFixture]
    public class UnitsNetTests
    {
        [Test]
        public void ConversionFromMillimeter()
        {
            var len = UnitsNet.Length.From(100, LengthUnit.Millimeter);
            Assert.IsTrue(len.Millimeters == 100);
        }

        [Test]
        public void ConversionFromMillimeterWithUnitAsString()
        {
            var unit = UnitsNet.Length.ParseUnit("mm");
            var len = UnitsNet.Length.From(100, unit);

            Assert.IsTrue(len.Millimeters == 100);
        }

        [Test]
        public void ConversionFromMillimeterWithSIFactor()
        {
            var len = Tests.Length.From(100, -3);

            Assert.IsTrue(len.Millimeters == 100);
        }
    }

    // Own Struct for Extension
    public struct Length
    {
        // New overload with SI Factor -> https://de.wikipedia.org/wiki/Meter
        public static UnitsNet.Length From(double val, int siFactor)
        {
            return new UnitsNet.Length(val * Math.Pow(10, siFactor));
        }
    }
}`

**Comment by anjdreas** [comment]
So, if I understand correctly, you want an easier way to construct `Length` and possibly other unit types with a value and an SI factor?

Is this a matter of simplifying the syntax so you can write
```
var length = new Length(val, siFactor);
```
instead of
```
var length = new Length(val * Math.Pow(10, siFactor));
```
?

**Comment by lordzero83** [comment]
Thats correct.
I want to happen the math inside the lib

**Comment by anjdreas** [comment]
Ok, I don't think this is a common enough scenario to justify adding it to the library and it is simple enough to handle outside the library. Would you agree?

**Comment by lordzero83** [comment]
Thats correct easy enough.
So i ´ll write my own small lib to do what your length does.
Need it in multiple programs and dont want to repeat that coding

**Comment by anjdreas** [comment]
Alright, closing this then.
