### ISSUE TITLE
Add linear mass density units

### ISSUE THREAD

**Issue by CaseyChester** [anjdreas/UnitsNet#237]
Linear mass density units (mass per unit length) are used heavily in textile engineering. Supporting the most common mass density units (see [linear density)](https://en.wikipedia.org/wiki/Linear_density) would be a good add to this library.

**Comment by anjdreas** [comment]
Sure! Sounds reasonable. Would you like to do a pull request on that? 

https://github.com/anjdreas/UnitsNet/blob/master/README.md#want-to-contribute

**Comment by anjdreas** [comment]
Following up here, do you intend to do a PR?

**Comment by anjdreas** [comment]
Closed due to inactivity, please reopen if you intend to pursue this.
