### ISSUE TITLE
.net 3.5 client profile 

### ISSUE THREAD

**Issue by fallenidol** [anjdreas/UnitsNet#242]
Readme indicates that the nuget package is compatible with .net 3.5 client profile, however when i attempt to use it in this scenario I get the following error...

Could not install package 'UnitsNet.WindowsRuntimeComponent 3.57.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v3.5,Profile=Client', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0

**Comment by anjdreas** [comment]
Hi, are you sure you are downloading the `UnitsNet` nuget, and not the `UnitsNet.WindowsRuntimeComponent` nuget?

**Comment by anjdreas** [comment]
Did that help?

**Comment by anjdreas** [comment]
Closed due to inactivity.
