### ISSUE TITLE
Proposal to add  "inch per second" to Speed

### ISSUE THREAD

**Issue by petgus** [anjdreas/UnitsNet#243]
I'll leave it to you to decide if it should be added. 
[https://en.wikipedia.org/wiki/Inch_per_second](https://en.wikipedia.org/wiki/Inch_per_second)

Thank you to all contributors for an excellent lib!

**Comment by anjdreas** [comment]
Sounds reasonable to me, will look at this more closely soon.

**Comment by anjdreas** [comment]
Oh I thought this was a PR when I read the email. Would you mind creating a pull request for this?

Steps on how to do that are outlined here:
https://github.com/anjdreas/UnitsNet#want-to-contribute

**Comment by gojanpaolo** [comment]
Is someone already doing this?
If not, I can do it. I'll also add Yards per second and Yards per minute

**Comment by anjdreas** [comment]
@gojanpaolo Please go ahead, no one else working on this to my knowledge. Reference this issue from the PR description text.
