### ISSUE TITLE
Add RotationalAcceleration

### ISSUE THREAD

**Issue by jebissey** [anjdreas/UnitsNet#245]
Hello,
We would need to convert from RadianPerSecondSquared to DegreesPerSecondSquared.
Greeting

**Comment by anjdreas** [comment]
Cool, would you care to do a pull request on that?
https://github.com/anjdreas/UnitsNet#want-to-contribute

**Comment by anjdreas** [comment]
Following up here, would you be interested in doing a pull request?

**Comment by plubbr** [comment]
This could probably be marked closed or resolved, right?

**Comment by anjdreas** [comment]
Yes, thanks
