### ISSUE TITLE
Serialization with .NET core / .NET standard

### ISSUE THREAD

**Issue by supermihi** [anjdreas/UnitsNet#255]
While the main nuget package appears to work well with dotnet core, UnitsNet.Serialization.JsonNet refuses to install in a dotnet core app because it targets only the net35 framework. Is it possible to build a nuget package targeting dotnet core or dotnet standard, or are there any dependencies on incompatible packages or system APIs?

**Comment by anjdreas** [comment]
Hi, good question. JSON.net is the only third party dependency and that should support netstandard. To my knowledge we don't use any .NET APIs that are not netstandard compliant, so I'm pretty sure this project could be converted to netstandard.

Would you mind taking a look and creating a pull request?
