### ISSUE TITLE
Parsing fails when mapped abbreviations contain numbers

### ISSUE THREAD

**Issue by plubbr** [anjdreas/UnitsNet#264]
Setting up by mapping an abbreviation to an unit:
`UnitSystem unitSystem = UnitSystem.GetCached("en-US");
            unitSystem.MapUnitToAbbreviation(UnitsNet.Units.AccelerationUnit.MeterPerSecondSquared, "m2");`

The then following works as expected, printing "MeterPerSecondSquared":
`Console.WriteLine(unitSystem.Parse<UnitsNet.Units.AccelerationUnit>("m2").ToString());`

But parsing from Acceleration , I expect "12 m/s²" but it throws exception 

> UnitsNetException: Error parsing string. The unit is not a recognized AccelerationUnit.

`Console.WriteLine(Acceleration.Parse("12 m2").ToString());`

It likely lies with the regular expression pattern in [UnitParser.ParseUnit](https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/CustomCode/UnitParser.cs#L50).

This is important for me because I am expecting to parse user-typed input. It is not reasonable for the user to enter the pretty input of m/s², but rather m/s^2 which has the same meaning.

I will fork and try to work it out.

**Comment by plubbr** [comment]
So I am a bit confused now... I wrote a [test](https://github.com/plubbr/UnitsNet/commit/2e78d2031a81dc69a4c79b0ff76f277c283e69bc) for the above conditions and it is passing in xunit. However, it fails with symbols (like ^). Will get a sample repo up tomorrow to compare to test results.

**Comment by anjdreas** [comment]
Huh, that is odd. Only thing I noticed was in your example you wrote `Acceleration.Parse("12 m2")` instead of `m/s^2`.

Also, UnitSystem is static and can cause problems if tests are run in parallel. I don't know how xunit is setup as I just recently switched to it. 

Look forward to see what you find.

**Comment by plubbr** [comment]
Yes, I removed the "^" while trying to troubleshoot and find the root cause. In my tests, I removed the `UnitSystem.ClearCache();` and it seems to work as it does in [this sample app](https://github.com/plubbr/UnitsNetAbbreviations).

Also, I found the issue is with this line in the regex parser:
[`@"(?<unit>[^\s\d,]+)", // capture Unit (non-whitespace) input`](https://github.com/anjdreas/UnitsNet/blob/master/UnitsNet/CustomCode/UnitParser.cs#L61).
It is not allowing any digits in the unit match. I am working on a solution now, but it will likely affect all generated unit classes (so extra attention during review would be appreciated).

**Comment by plubbr** [comment]
Thanks for the follow up on the PR. This is a very useful project!

**Comment by anjdreas** [comment]
Great! I'm glad you enjoy it.
