### ISSUE TITLE
Errors occurred when executing "build.bat"

### ISSUE THREAD

**Issue by ngeslin** [anjdreas/UnitsNet#279]
An error occurred when I tried to execute "build.bat". I would like to be sure that it's caused by my environment or not.

When executing the original script, I have the following error:

>WindowsRuntimeComponent project not yet supported by dotnet CLI, using MSBuild15 instead
C:\GitHub\UnitsNet\Build\build.ps1 : Failed to build.
>System.Management.Automation.CommandNotFoundException: The term "msbuild" is not recognized as a cmdlet name, function, script file, or executable program. Check the spelling of the name, or if a path exists, verify that the path is correct and try again.
>   à System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
>   à System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
>   à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
>   à System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)' ]
>    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
>    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,build.ps1

Commenting all lines related to UnitsNet.Tests.WindowsRuntimeComponent (I have no use of it) prevents the error. Instead I have the following message:

>Unhandled Exception: System.InvalidOperationException: Specify which project file to use because this 'C:\GitHub\UnitsNet\UnitsNet.Tests' contains more than one project file.
>   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProjPath(String projectDirectory)
>   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProj(String projectDirectory, NuGetFramework framework, String configuration, String outputPath)
>   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectTools(CommandResolverArguments commandResolverArguments)
>   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
>   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolverArguments commandResolverArguments)
>   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
>   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
>   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`1 args, NuGetFramework framework, String configuration, String outputPath, String applicationName)
>   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemetryClient)
>   at Microsoft.DotNet.Cli.Program.Main(String[] args)

This one occurs when running the tests. I do not understand how this script can work if UnitsNet.Tests contains both "UnitsNet.Tests.csproj" and "UnitsNet.Tests.NetCore.csproj".

Am I missing something ?

**Comment by anjdreas** [comment]
Hi, do you have Visual Studio 2017 and .NET Core 1.1 SDK installed?

The first error was due to not finding msbuild, and I have PATH environment variable set to include `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin`. I don't recall if I added this myself or if VS did on its own. This all runs on AppVeyor build server with no particular environment other than VS2017, so I would think VS installer sets this environment variable.

Regarding second error, try updating to the latest `master` branch. Two csproj files were merged into one file some time ago. There should be only one .csproj file here:
https://github.com/anjdreas/UnitsNet/tree/master/UnitsNet.Tests

It does, however, target two frameworks; `netcoreapp1.1` and `net462`. 
We use `dotnet xunit test` with parameter `-framework netcoreapp1.1` to run tests, which should tell it what target framework to use.

**Comment by ngeslin** [comment]
Thanks for your anwser and the details, I'll look at my VS 2017 installer and configuration. I did not work on the project for 3 months, so I was a bit surprised by all the changes.

**Comment by anjdreas** [comment]
Yeah, the biggest change was migrating to netstandard and the new `dotnet` CLI tooling. Let me know if you can't figure it out.
