### ISSUE TITLE
Volume from Mass / Density operator missing.

### ISSUE THREAD

**Issue by ThomasN-Saab** [anjdreas/UnitsNet#283]
I believe it should look something like the code snippet below and be placed in UnitsNet/CustomCode/UnitClasses/Mass.extra.cs
I'd like to leave actually putting it in the project to someone more involved with the development and also more experienced with GitHub than myself.

    public static Volume operator/(Mass mass, Density density)
    {
    	return Volume.FromCubicMeters(mass.Kilograms / density.KilogramsPerCubicMeter);
    }

**Comment by anjdreas** [comment]
Hi, you are absolutely correct about the code snippet and where to put it. Would you mind doing a pull request? I really prefer if the person with the idea adds it.

**Comment by ThomasN-Saab** [comment]
I didn't want to do it because I'm not very familiar with GitHub and I haven't forked a project before. I've done it now though and made the pull request.
I guess this was a nice learning experience.

**Comment by anjdreas** [comment]
Fixed by #284
