### ISSUE TITLE
AutoUnitRecognizing

### ISSUE THREAD

**Issue by Bijan86** [anjdreas/UnitsNet#75]
Hi
i am working with a lot of numeric data in engineering field and using UNITSNET in my code.
because of different units always i should be careful about units and it makes hard in coding.
BUT:
if there was an ability for this library that from two base unit (length and force) easily it can find out what other units are. i mean that imagine for a set of data length is in "m" (meter) and force is in "N" (Newton) so other units are:
Torque: N-m
Pressure: N/m^2
Area: m^2
Volume: m^3
Density: N/m^3
So I have a Suggestion For This:
In "unitsnet>units" name space , add functions for each unit that can be recognize by other units,
Example in VB.NET Language:

imports Unitsnet.units
Function Torqueunit (Length as units.length, force as units.force) as units.torque
Dim Result As Units.torque
if length=length.meter and force=force.Newton then
   result=Torque.newtonmeter
elseif length=length.centimetermeter and force=force.Newton then
 result=Torque.newtoncentimeter
elseif . . .
endif
Return Result
End Function

**Comment by anjdreas** [comment]
If I understand correctly, you want to automatically determine the unit after a calculation?
Say 100N x 1m = 100N-m ?

So there is a simple way and a hard way.

The simple way is explicitly implementing the derived types we know and care about, such as ```Torque t = Force.FromNewtons(100) * Length.FromMeters(1);```

This doesn't give you the derived unit, such as Newtonmeters, Newtonmillimeters and so on. It only gives you the calculated Torque.

The way you proposed could also work, something like this:
```
TorqueUnit tu; // Is assigned TorqueUnit.Newtonmeter
Torque t = Torque.FromForceLength(100, 1, ForceUnit.Newton, LengthUnit.Meter, out tu);
```

The hard way is to determine the derived unit in a generic way, something like 
```
TorqueUnit tu; // Is assigned TorqueUnit.Newtonmeter
Torque t = Torque.Parse("100N * 1m", out tu);
```

I don't have any experience with this type of implementation, but it sounds like it could possibly be complicated. Simple cases like multiplication and division of typical units like the ones you listed might be solved by a naive solution in the direction of:
```
Torque: 100N x 1m => N x m => 100 N-m
Pressure: 100N / 2m / 5m => N/m/m => 10 N/m²
```
I can see it getting more complicated when you come across not so standard units:
```
Torque: 1kgf x 1mm => kgf x mm => 1 kgf-mm
```
In this case I assume it is common to round to the nearest convention of units, such as N-m or maybe N-mm. Solving that behavior in a predictable, intuitive manner might be tricky.

I'm all for doing something like this, but I am not the right person to implement it.
I know F# has native support for this exact thing, but that doesn't help us. There is a nice list of open source projects regarding units over [here](https://github.com/objorke/QuantityTypes), maybe some of them can be of inspiration.

**Comment by Bijan86** [comment]
Thanks From Explanations ( Learned New Things).

I should explain more What Exactly I mean. Imagine that you have a data text file that contains a set of numbers like below:

"
Force     -     Length     -      Torque     -     Volume     -     Density     -     Area     -     unit
------------------------------------------------------------------------------------------------------------------
10          -        23         -      230          -      6000        -       51           -       400     -    N-m
15          -        12         -      180          -      2200        -       21           -       12       -    Ton-cm
. . .
"
So As you see in each line we have a independent unit system and we want read data and store them in some variables that we provided from Unitsnet library, so for each line in frst step i have to detect Force unit and Length unit (from last column) and according them I should Find Other Data units, For Example in first line of top data Because units is "N" and "m" so we can say 
torque=230 N-m
Volume =6000 m^3 
Density=51 N/m^3
Area= 400 m^2 
and Also For Second Line Because units is "ton" an "cm" so we can say that:
torque=180 Ton-cm
Volume =2200 cm^3 
Density=21 Ton/cm^3
Area= 12 cm^2 
Now I think You Understand what is exactly my Problem is and i think with suggestion in first comment we can provide this ability.

**Comment by Bijan86** [comment]
Also As you said in your comment this ability can help to calculations and it is very similar to example that you said:
Torque t = Torque.FromForceLength(100, 1, ForceUnit.Newton, LengthUnit.Meter, out tu);
and by this ability we don't needs functions like  Torque.FromForceLength() and its do it speratly, and also MANY FUNCTION THAT WE HAVE ADDED TO LIBRARY CAN BE CLEAN AND WE DON'T NEED THEM, I mean Input Functions that started by "from" like "fromNewtonMeter()" or "FromNewtonCentimeter()" or ... , and only alone "from()" function is enough and bye this ability user can add or determine the unit of any number.

**Comment by anjdreas** [comment]
I think I understand what you mean, but I'm in no way 100% sure :-) I really don't understand how that text file you described works. Are the numbers multiplied with each other for each row? How are the units N-m and Ton-cm applied?

If I understand correctly, you want a method to return the unit that is determined by its input alone?
Example pseudo code:
```
var result = From(100, ForceUnit.Newton, 1, LengthUnit.Meter);
// result.Value is 100
// result.Unit is TorqueUnit.Newtonmeter
```

Is this what you had in mind? If so, what happens if I do:
```
var result = From(100, ForceUnit.Newton, 5, SpeedUnit.KilometersPerHour, 3, PressureUnit.Pascal);
// result.Value is ?
// result.Unit is ?
```

**Comment by Bijan86** [comment]
First Example in near to what i want,
var result = From(100, ForceUnit.Newton, 1, LengthUnit.Meter);
Function automatically calculate the unit of Torque. Now imagine a function that only calculate the unit (not value), For example for torque it need length unit and force unit then it say according these units , what will be torque unit (absolutely result unit should be available in  Torque units enum).
For better understanding Imagine we have this function that it's name is Torqueunit so above code be in this way:
var resultunit = Torqueunit (ForceUnit.Newton, LengthUnit.Meter);
var result = From(100*1,resultunit );

**Comment by Bijan86** [comment]
Let me Show You Below Code in VB.Net:
----------------------------------------------------------------------------------------------------------------
Public Class UnitDistiction
        Function Pressureunit(ByVal Lenghtunit As Units.LengthUnit, ByVal Forceunit As Units.ForceUnit) As Units .PressureUnit Handles
            If Lenghtunit = Units.LengthUnit.Inch And Forceunit = Units.ForceUnit.PoundForce Then
                Return Units.PressureUnit.PoundForcePerSquareInch
            ElseIf Lenghtunit = Units.LengthUnit.Foot And Forceunit = Units.ForceUnit.PoundForce Then
                Return Units.PressureUnit.PoundForcePerSquareFoot
            ElseIf Lenghtunit = Units.LengthUnit.Inch And Forceunit = Units.ForceUnit.KiloPond Then
                Return Units.PressureUnit.KilopoundForcePerSquareInch
            ElseIf Lenghtunit = Units.LengthUnit.Foot And Forceunit = Units.ForceUnit.KiloPond Then
                Return Units.PressureUnit.KilopoundForcePerSquareFoot
            ElseIf Lenghtunit = Units.LengthUnit.Millimeter And Forceunit = Units.ForceUnit.Kilonewton Then
                Return Units.PressureUnit.KilonewtonPerSquareMillimeter
            ElseIf Lenghtunit = Units.LengthUnit.Meter And Forceunit = Units.ForceUnit.Kilonewton Then
                Return Units.PressureUnit.KilonewtonPerSquareMeter
            ElseIf Lenghtunit = Units.LengthUnit.Millimeter And Forceunit = Units.ForceUnit.KilogramForce Then
                Return Units.PressureUnit.KilogramForcePerSquareMillimeter
            ElseIf Lenghtunit = Units.LengthUnit.Meter And Forceunit = Units.ForceUnit.KilogramForce Then
                Return Units.PressureUnit.KilogramForcePerSquareMeter
            ElseIf Lenghtunit = Units.LengthUnit.Millimeter And Forceunit = Units.ForceUnit.Newton Then
                Return Units.PressureUnit.NewtonPerSquareMillimeter
            ElseIf Lenghtunit = Units.LengthUnit.Meter And Forceunit = Units.ForceUnit.Newton Then
                Return Units.PressureUnit.NewtonPerSquareMeter
            ElseIf Lenghtunit = Units.LengthUnit.Millimeter And Forceunit = Units.ForceUnit.TonneForce Then
                Return Units.PressureUnit.TonneForcePerSquareMillimeter
            ElseIf Lenghtunit = Units.LengthUnit.Meter And Forceunit = Units.ForceUnit.TonneForce Then
                Return Units.PressureUnit.TonneForcePerSquareMeter
            ElseIf Lenghtunit = Units.LengthUnit.Centimeter And Forceunit = Units.ForceUnit.Kilonewton Then
                Return Units.PressureUnit.KilonewtonPerSquareCentimeter
            ElseIf Lenghtunit = Units.LengthUnit.Centimeter And Forceunit = Units.ForceUnit.KilogramForce Then
                Return Units.PressureUnit.KilogramForcePerSquareCentimeter
            ElseIf Lenghtunit = Units.LengthUnit.Centimeter And Forceunit = Units.ForceUnit.Newton Then
                Return Units.PressureUnit.NewtonPerSquareCentimeter
            ElseIf Lenghtunit = Units.LengthUnit.Centimeter And Forceunit = Units.ForceUnit.TonneForce Then
                Return Units.PressureUnit.TonneForcePerSquareCentimeter
            End If
        End Function

    End Class
-------------------------------------------------------------------------------------------------------------------
this code causes that pressure unit distinct easily according existing length and force units.

**Comment by anjdreas** [comment]
Ok, I think I understand better now what it is you want. Basically, you just want Units.NET to help you figure out the pressure unit after calculating pressure from area and force?

I don't think the naming is intuitive in this case, since Length is 2-dimensional (area). There are some similar methods already, but they only output the magnitude, not the unit:
```csharp
        public static Force FromPressureByArea(Pressure p, Area area)
        {
            double newtons = p.Pascals*area.SquareMeters;
            return new Force(newtons);
        }
```

We could modify this with overload, like this:
```csharp
        public static Force FromPressureByArea(Pressure p, Area area, out ForceUnit unit)
        {
            unit = ;// determine unit, like in your code snippet
            double newtons = p.Pascals*area.SquareMeters;
            return new Force(newtons);
        }
```

What do you think?
I'm thinking maybe both. One method to just determine the unit `ex: PressureUnit.Pascal` in certain contexts like `Force.FromPressureByArea()` or `Pressure.FromForceByArea()`, and one method to output both the unit `ex: PressureUnit.Pascal` and the quantity `ex: 153`.



I converted your VB code to C# for reference:
```csharp
public class UnitDistiction
{
    public Units.PressureUnit Pressureunit(Units.LengthUnit Lenghtunit, Units.ForceUnit Forceunit)
    {
        if (Lenghtunit == Units.LengthUnit.Inch & Forceunit == Units.ForceUnit.PoundForce) {
            return Units.PressureUnit.PoundForcePerSquareInch;
        } else if (Lenghtunit == Units.LengthUnit.Foot & Forceunit == Units.ForceUnit.PoundForce) {
            return Units.PressureUnit.PoundForcePerSquareFoot;
        } else if (Lenghtunit == Units.LengthUnit.Inch & Forceunit == Units.ForceUnit.KiloPond) {
            return Units.PressureUnit.KilopoundForcePerSquareInch;
        } else if (Lenghtunit == Units.LengthUnit.Foot & Forceunit == Units.ForceUnit.KiloPond) {
            return Units.PressureUnit.KilopoundForcePerSquareFoot;
        } else if (Lenghtunit == Units.LengthUnit.Millimeter & Forceunit == Units.ForceUnit.Kilonewton) {
            return Units.PressureUnit.KilonewtonPerSquareMillimeter;
        } else if (Lenghtunit == Units.LengthUnit.Meter & Forceunit == Units.ForceUnit.Kilonewton) {
            return Units.PressureUnit.KilonewtonPerSquareMeter;
        } else if (Lenghtunit == Units.LengthUnit.Millimeter & Forceunit == Units.ForceUnit.KilogramForce) {
            return Units.PressureUnit.KilogramForcePerSquareMillimeter;
        } else if (Lenghtunit == Units.LengthUnit.Meter & Forceunit == Units.ForceUnit.KilogramForce) {
            return Units.PressureUnit.KilogramForcePerSquareMeter;
        } else if (Lenghtunit == Units.LengthUnit.Millimeter & Forceunit == Units.ForceUnit.Newton) {
            return Units.PressureUnit.NewtonPerSquareMillimeter;
        } else if (Lenghtunit == Units.LengthUnit.Meter & Forceunit == Units.ForceUnit.Newton) {
            return Units.PressureUnit.NewtonPerSquareMeter;
        } else if (Lenghtunit == Units.LengthUnit.Millimeter & Forceunit == Units.ForceUnit.TonneForce) {
            return Units.PressureUnit.TonneForcePerSquareMillimeter;
        } else if (Lenghtunit == Units.LengthUnit.Meter & Forceunit == Units.ForceUnit.TonneForce) {
            return Units.PressureUnit.TonneForcePerSquareMeter;
        } else if (Lenghtunit == Units.LengthUnit.Centimeter & Forceunit == Units.ForceUnit.Kilonewton) {
            return Units.PressureUnit.KilonewtonPerSquareCentimeter;
        } else if (Lenghtunit == Units.LengthUnit.Centimeter & Forceunit == Units.ForceUnit.KilogramForce) {
            return Units.PressureUnit.KilogramForcePerSquareCentimeter;
        } else if (Lenghtunit == Units.LengthUnit.Centimeter & Forceunit == Units.ForceUnit.Newton) {
            return Units.PressureUnit.NewtonPerSquareCentimeter;
        } else if (Lenghtunit == Units.LengthUnit.Centimeter & Forceunit == Units.ForceUnit.TonneForce) {
            return Units.PressureUnit.TonneForcePerSquareCentimeter;
        }
    }
}
```

**Comment by Bijan86** [comment]
We have some basic units that all units derive from them.
in engineering we have Force, Length, Temperature and Time.
any other units can derive from them if we specify them. exactly like unit systems, (http://en.wikipedia.org/wiki/International_System_of_Units)
When we choose one unit system , all of units can be determine from that choose,
for example imagine we choose SI unit system as shows in above reference, 
So Force = N, Length=m, time=S, Temp=C
Now all other units can obtain from some of them or all of them:
Pressure=N/m^2, Torque=N.m, Density=N*S^2/m^4, Specific Weight=N/m^3 and . . .,

As we see in above example some units can determine only by two basically units or three basically units, for example only pressure needs Force and length units to determine its unit and density needs three basically units to determine its unit,

according these explanations we should decide to how this library works, I think that right method is that each unit can be determines with its basically needs, like your converted code in above from vb.net to c#.

Beside of that also you suggestions codes is good and library also need them. 
I want to explain why users need both of these methods:
when we have units and its values in our units classes , each value with its units are specified, so because units are specified with your suggestion other units from them can be derive beside of calculating result value like your example : 

  public static Force FromPressureByArea(Pressure p, Area area)
        {
            double newtons = p.Pascals*area.SquareMeters;
            return new Force(newtons);
        }

But in other times programmer needs some numbers from user and user only specifies basically units or define unit system (it is hard to ask any time from user that what is the units of you value for each unit) , so with suggestion code we can determine the unit of each  value that user enter to program, for example we ask only from user that what is your length and force unit, and imagine that he answered m and N, So if he should enter Pressure, Torque , Density and ... we don't need to ask him in each step what is you unit and easily bye something like : 
public Units.PressureUnit Pressureunit(Units.LengthUnit Lenghtunit, Units.ForceUnit Forceunit)
we can determines its unit, and when user enter each value we know its unit, for example if user enter the value of pressure we know that the unit of this value is N/m^2 and easily we can determine it's pressure object:
dim prsurunit as units.pressure=Pressureunit(Units.LengthUnit Lenghtunit, Units.ForceUnit Forceunit)
dim prsur as new unitsnet.pressure
prsur=pressure.from(uservalue,  prsurunit )

Hope that can explain my idea

**Comment by anjdreas** [comment]
Sorry for not following up on this, but I don't have the time to spend on this. Reopen if you or someone else wants to continue this.
