### ISSUE TITLE
silverlight 5 support

### ISSUE THREAD

**Issue by vgrafe** [anjdreas/UnitsNet#77]
Hi, 

Trying to deploy via Nuget package manager, the following error pops up : 

Successfully installed 'UnitsNet 3.12.0'.
Successfully uninstalled 'UnitsNet 3.12.0'.
Install failed. Rolling back...
Could not install package 'UnitsNet 3.12.0'. You are trying to install this package into a project that targets 'Silverlight,Version=v5.0', but the package does not contain any assembly references that are compatible with that framework. For more information, contact the package author. 

The readme lists silverlight 5 as one of the target environments, can you direct me towards any previous release that supports it?

**Comment by anjdreas** [comment]
Hi, I honestly don't know. To my knowledge PCL profile 328 should be compatible with Silverlight 5, but I have not tried it myself. I'd have to google a bit to see if this is a known issue. 

Are you able to install any other nugets from the same project? If you can list one or more open source nugets that are working, then I can see what they are doing differently and hopefully spot the problem.

**Comment by anjdreas** [comment]
Were you able to test this out on other SL5 projects?

**Comment by vgrafe** [comment]
sorry about the delay. After those few tries, I decided to write my own library and moved on.

**Comment by anjdreas** [comment]
Fair enough, thanks anyway. I'll leave this one open as there is probably something that needs to be done here, and I don't have time to look at it myself.

**Comment by anjdreas** [comment]
Closing this due to lack of interest.
