### ISSUE TITLE
More energy units support

### ISSUE THREAD

**Issue by FabioCZ** [anjdreas/UnitsNet#85]
Include more energy units, some of the most used ones from here: https://en.wikipedia.org/wiki/Units_of_energy - calories, BTU, eV, ft lb, erg, Wh

**Comment by FabioCZ** [comment]
pull request #86

**Comment by FabioCZ** [comment]
Units test results: 
![energy_test_result](https://cloud.githubusercontent.com/assets/1450700/8093822/7a0379ec-0f80-11e5-8f45-d83d115c608b.PNG)

**Comment by anjdreas** [comment]
See #86 for info.
