### ISSUE TITLE
Thread-safety issue

### ISSUE THREAD

**Issue by istanishev** [anjdreas/UnitsNet#98]
UnitSystem class is using static Dictionary [here](https://github.com/anjdreas/UnitsNet/blob/b2d853bd7d1f9bc494377ecec51ff1ac8241fdd3/UnitsNet/CustomCode/UnitSystem.cs#L37) which makes the class not thread-safe.

UnitSystem.GetCached is used from the Parse() method which makes the Parse method also not thread-safe.

The result is NullReferenceException.

Sample stack trace:
at System.Collections.Generic.Dictionary.Insert(TKey key, TValue value, Boolean add)
at System.Collections.Generic.Dictionary.set_Item(TKey key, TValue value)
at UnitsNet.UnitSystem.GetCached(IFormatProvider cultureInfo)
at UnitsNet.Mass.ParseUnit(String str, IFormatProvider formatProvider)
at UnitsNet.Mass.ParseWithRegex(String regexString, String str, IFormatProvider formatProvider)
...

**Comment by anjdreas** [comment]
Hm, good catch. Would you mind creating a pull request for this?

I don't see exactly what is giving the null ref exception in this case? 
Will a lock() statement in GetCached() do the trick, or do we need to resort to ConcurrentDictionary?

**Comment by istanishev** [comment]
The exception happens randomly and it comes from within the Dictionary class. The heavier the parallelism, the more frequently it happens. I can't really pinpoint the exact location inside the .net framework though.

I think both would work - lock & ConcurrentDictionary. Maybe using the ConcurrentDictionary would be a bit cleaner solution. 

Sure, I'll be happy to create a pull-request ;)

**Comment by anjdreas** [comment]
I think we need a lock inside GetCached() at least, to ensure it's initialized just once per culture. As for ConcurrentDictionary, depends on the implementation of Dictionary really. I suppose it's safest to use it though.

**Comment by anjdreas** [comment]
Just checking in, any progress on this?

**Comment by istanishev** [comment]
Hi Andreas,

Sorry for the delay, I'm on vacation right now and I can create the pull-request next week the earliest.

Cheers ;)

**Comment by anjdreas** [comment]
No problems, take your time. Thanks for the notice.

**Comment by anjdreas** [comment]
And enjoy your vacation :-)

**Comment by anjdreas** [comment]
Nuget 3.19.1 is now out.
